/* 成语补充库：用于把成语总数补足到 1200 且不重复。
 * 字段同主库 id/word/pinyin/tier/meaning/distinguish/example/trap。
 * tier 仅为占位，构建时会按最终顺序重新分级（前300必考/中400高频/后500低频）。
 */
const IDIOMS_FILLER = [
  { id: 1201, word: '安居乐业', pinyin: 'ān jū lè yè', tier: '低频',
    meaning: '安定地生活、愉快地工作。',
    distinguish: '褒义，指生活安定、工作顺心。',
    example: '百姓安居乐业，天下太平。',
    trap: '指安定快乐的生活。' },
  { id: 1202, word: '安分守己', pinyin: 'ān fèn shǒu jǐ', tier: '低频',
    meaning: '规矩老实，守本分。',
    distinguish: '指安于本分、不惹事。',
    example: '他安分守己，从不生事。',
    trap: '指守本分。' },
  { id: 1203, word: '按部就班', pinyin: 'àn bù jiù bān', tier: '低频',
    meaning: '按照一定的条理、步骤做事。',
    distinguish: '中性，指按程序；有时也指拘泥。',
    example: '工作按部就班推进。',
    trap: '指按步骤进行。' },
  { id: 1204, word: '暗度陈仓', pinyin: 'àn dù chén cāng', tier: '低频',
    meaning: '比喻暗中进行某种活动（多指正面迷惑、暗地里行动）。',
    distinguish: '常与「明修栈道」连用。',
    example: '他明修栈道，暗度陈仓。',
    trap: '指暗中进行。' },
  { id: 1205, word: '傲然挺立', pinyin: 'ào rán tǐng lì', tier: '低频',
    meaning: '坚强不屈地直立着。',
    distinguish: '多形容松柏、人也指气节。',
    example: '青松傲然挺立。',
    trap: '指坚强直立。' },
  { id: 1206, word: '白驹过隙', pinyin: 'bái jū guò xì', tier: '低频',
    meaning: '白马穿过缝隙，形容时间过得极快。',
    distinguish: '指时光飞逝。',
    example: '人生如白驹过隙。',
    trap: '指时间飞快。' },
  { id: 1207, word: '百废待兴', pinyin: 'bǎi fèi dài xīng', tier: '低频',
    meaning: '许多被废置的事业都等着兴办。',
    distinguish: '指事业待恢复；与「百废俱兴」反义。',
    example: '战后百废待兴。',
    trap: '指待兴办。' },
  { id: 1208, word: '百感交集', pinyin: 'bǎi gǎn jiāo jí', tier: '低频',
    meaning: '各种感想交织在一起。',
    distinguish: '指感触很多。',
    example: '故地重游，百感交集。',
    trap: '指感慨万千。' },
  { id: 1209, word: '班门弄斧', pinyin: 'bān mén nòng fǔ', tier: '低频',
    meaning: '在鲁班门前舞弄斧头，比喻在行家面前卖弄本领。',
    distinguish: '谦辞/贬义，指不自量力。',
    example: '在专家面前班门弄斧。',
    trap: '指在行家前显摆。' },
  { id: 1210, word: '包罗万象', pinyin: 'bāo luó wàn xiàng', tier: '低频',
    meaning: '内容丰富，应有尽有。',
    distinguish: '指内容广博。',
    example: '这部丛书包罗万象。',
    trap: '指内容广泛。' },
  { id: 1211, word: '饱经沧桑', pinyin: 'bǎo jīng cāng sāng', tier: '低频',
    meaning: '经历过很多世事变迁。',
    distinguish: '指阅历深。',
    example: '老人饱经沧桑。',
    trap: '指阅历丰富。' },
  { id: 1212, word: '暴风骤雨', pinyin: 'bào fēng zhòu yǔ', tier: '低频',
    meaning: '来势急遽而猛烈的风雨，比喻声势浩大的运动。',
    distinguish: '指猛烈；与「和风细雨」反义。',
    example: '革命如暴风骤雨。',
    trap: '指猛烈急速。' },
  { id: 1213, word: '杯弓蛇影', pinyin: 'bēi gōng shé yǐng', tier: '低频',
    meaning: '将映在杯中的弓影误认作蛇，比喻疑神疑鬼、自惊自怕。',
    distinguish: '指无端恐惧。',
    example: '他杯弓蛇影，疑神疑鬼。',
    trap: '指疑惧自扰。' },
  { id: 1214, word: '杯水车薪', pinyin: 'bēi shuǐ chē xīn', tier: '低频',
    meaning: '用一杯水去救一车着火的柴，比喻力量太小无济于事。',
    distinguish: '指力量微薄。',
    example: '捐款如杯水车薪。',
    trap: '指无济于事。' },
  { id: 1215, word: '悲欢离合', pinyin: 'bēi huān lí hé', tier: '低频',
    meaning: '泛指聚会、别离、欢乐、悲哀的种种遭遇。',
    distinguish: '指人生际遇。',
    example: '人生悲欢离合。',
    trap: '指聚散哀乐。' },
  { id: 1216, word: '本末倒置', pinyin: 'běn mò dào zhì', tier: '低频',
    meaning: '把根本和枝节弄颠倒，比喻把主次、轻重弄反。',
    distinguish: '指主次颠倒。',
    example: '抓细节而忘目标，本末倒置。',
    trap: '指主次颠倒。' },
  { id: 1217, word: '逼上梁山', pinyin: 'bī shàng liáng shān', tier: '低频',
    meaning: '比喻被迫做某种事（原指被逼上梁山起义）。',
    distinguish: '指被迫无奈。',
    example: '他走投无路，逼上梁山。',
    trap: '指被迫而为。' },
  { id: 1218, word: '鞭长莫及', pinyin: 'biān cháng mò jí', tier: '低频',
    meaning: '鞭子虽长，打不到马肚子，比喻力量达不到。',
    distinguish: '指力不能及。',
    example: '远在国外，鞭长莫及。',
    trap: '指力量达不到。' },
  { id: 1219, word: '变幻莫测', pinyin: 'biàn huàn mò cè', tier: '低频',
    meaning: '变化多端，难以推测。',
    distinguish: '指变化无常。',
    example: '局势变幻莫测。',
    trap: '指变化难测。' },
  { id: 1220, word: '别出心裁', pinyin: 'bié chū xīn cái', tier: '低频',
    meaning: '另有一种构思或设计，指独创一格。',
    distinguish: '褒义，指构思新奇。',
    example: '设计别出心裁。',
    trap: '指独创一格。' },
  { id: 1221, word: '别具匠心', pinyin: 'bié jù jiàng xīn', tier: '低频',
    meaning: '具有与众不同的巧妙构思。',
    distinguish: '褒义，指构思巧妙。',
    example: '园林别具匠心。',
    trap: '指构思精巧。' },
  { id: 1222, word: '别开生面', pinyin: 'bié kāi shēng miàn', tier: '低频',
    meaning: '另外开创一种新的形式或局面。',
    distinguish: '指开创新局面。',
    example: '晚会别开生面。',
    trap: '指新局面。' },
  { id: 1223, word: '宾至如归', pinyin: 'bīn zhì rú guī', tier: '低频',
    meaning: '客人到这里像回到自己家，形容招待热情。',
    distinguish: '指待客周到。',
    example: '旅馆宾至如归。',
    trap: '指待客如家。' },
  { id: 1224, word: '冰清玉洁', pinyin: 'bīng qīng yù jié', tier: '低频',
    meaning: '像冰一样清明、玉一样纯洁，比喻人品高尚纯洁。',
    distinguish: '褒义，指品德高洁。',
    example: '她冰清玉洁，令人敬重。',
    trap: '指品德纯洁。' },
  { id: 1225, word: '并行不悖', pinyin: 'bìng xíng bù bèi', tier: '低频',
    meaning: '同时进行，不相冲突。',
    distinguish: '指两事可共存。',
    example: '发展与环保并行不悖。',
    trap: '指不冲突。' },
  { id: 1226, word: '病入膏肓', pinyin: 'bìng rù gāo huāng', tier: '低频',
    meaning: '病到无法医治，比喻事态严重无法挽救。',
    distinguish: '指无可救药。',
    example: '积弊已病入膏肓。',
    trap: '指无法挽救。' },
  { id: 1227, word: '波澜壮阔', pinyin: 'bō lán zhuàng kuò', tier: '低频',
    meaning: '比喻气势宏伟浩大。',
    distinguish: '多指场面、运动。',
    example: '历史波澜壮阔。',
    trap: '指气势宏大。' },
  { id: 1228, word: '博古通今', pinyin: 'bó gǔ tōng jīn', tier: '低频',
    meaning: '对古代的事知道很多，又通晓现代的事。',
    distinguish: '褒义，指学识渊博。',
    example: '他博古通今，学养深厚。',
    trap: '指学识广博。' },
  { id: 1229, word: '博闻强识', pinyin: 'bó wén qiáng zhì', tier: '低频',
    meaning: '见闻广博，记忆力强。',
    distinguish: '褒义，指博学强记。',
    example: '学者博闻强识。',
    trap: '指见闻广、记性强。' },
  { id: 1230, word: '不动声色', pinyin: 'bù dòng shēng sè', tier: '低频',
    meaning: '内心活动不从语气和神态上流露。',
    distinguish: '指镇定、不露声色。',
    example: '他不动声色地布局。',
    trap: '指镇定不露。' },
  { id: 1231, word: '不寒而栗', pinyin: 'bù hán ér lì', tier: '低频',
    meaning: '不冷却发抖，形容非常恐惧。',
    distinguish: '指极度害怕。',
    example: '回忆令人不寒而栗。',
    trap: '指恐惧。' },
  { id: 1232, word: '不即不离', pinyin: 'bù jí bù lí', tier: '低频',
    meaning: '不亲近也不疏远，指关系恰当。',
    distinguish: '指保持恰当距离。',
    example: '相处不即不离。',
    trap: '指不远不近。' },
  { id: 1233, word: '不胫而走', pinyin: 'bù jìng ér zǒu', tier: '低频',
    meaning: '没有腿却能跑，形容消息传播迅速。',
    distinguish: '指消息传得快。',
    example: '消息不胫而走。',
    trap: '指传播迅速。' },
  { id: 1234, word: '不堪设想', pinyin: 'bù kān shè xiǎng', tier: '低频',
    meaning: '事情的结果不能想象，指后果很严重。',
    distinguish: '指后果严重。',
    example: '若失控，不堪设想。',
    trap: '指后果严重。' },
  { id: 1235, word: '不刊之论', pinyin: 'bù kān zhī lùn', tier: '低频',
    meaning: '不可改动或不可磨灭的言论，形容论断精当。',
    distinguish: '褒义，指至理名言；"刊"指删改。',
    example: '此乃不刊之论。',
    trap: '指不可改的精论。' },
  { id: 1236, word: '不可理喻', pinyin: 'bù kě lǐ yù', tier: '低频',
    meaning: '没法用道理使他明白，形容固执或蛮横。',
    distinguish: '贬义，指蛮不讲理。',
    example: '他蛮横不可理喻。',
    trap: '指蛮横不明理。' },
  { id: 1237, word: '不劳而获', pinyin: 'bù láo ér huò', tier: '低频',
    meaning: '自己不劳动而占有别人的劳动成果。',
    distinguish: '贬义，指坐享其成。',
    example: '财富不劳而获可耻。',
    trap: '贬义，指坐享。' },
  { id: 1238, word: '不谋而合', pinyin: 'bù móu ér hé', tier: '低频',
    meaning: '事前没有商量而彼此见解相同。',
    distinguish: '指意见巧合一致。',
    example: '两人想法不谋而合。',
    trap: '指不约而同。' },
  { id: 1239, word: '不期而遇', pinyin: 'bù qī ér yù', tier: '低频',
    meaning: '没有约定而意外相遇。',
    distinguish: '指偶然相遇。',
    example: '故友不期而遇。',
    trap: '指偶遇。' },
  { id: 1240, word: '不速之客', pinyin: 'bù sù zhī kè', tier: '低频',
    meaning: '没有邀请而自己来的客人。',
    distinguish: '指未经邀约的客人。',
    example: '不速之客来访。',
    trap: '指不邀自来者。' },
  { id: 1241, word: '不务正业', pinyin: 'bù wù zhèng yè', tier: '低频',
    meaning: '不从事正当的职业，也指不搞好本职工作。',
    distinguish: '贬义，指荒废本职。',
    example: '他整日游荡，不务正业。',
    trap: '贬义，指荒废正业。' },
  { id: 1242, word: '不屑一顾', pinyin: 'bù xiè yī gù', tier: '低频',
    meaning: '认为不值得一看，形容极端轻视。',
    distinguish: '指非常轻视。',
    example: '他对名利不屑一顾。',
    trap: '指极为轻视。' },
  { id: 1243, word: '不言而喻', pinyin: 'bù yán ér yù', tier: '低频',
    meaning: '不用说话就能明白，形容道理很明显。',
    distinguish: '指明显易懂。',
    example: '其理不言而喻。',
    trap: '指明显显然。' },
  { id: 1244, word: '不翼而飞', pinyin: 'bù yì ér fēi', tier: '低频',
    meaning: '没有翅膀却能飞，比喻东西突然丢失，也比喻消息传播快。',
    distinguish: '指丢失或传得快。',
    example: '文件不翼而飞。',
    trap: '指忽然丢失/传开。' },
  { id: 1245, word: '不约而同', pinyin: 'bù yuē ér tóng', tier: '低频',
    meaning: '没有事先约定而彼此行动一致。',
    distinguish: '指默契一致。',
    example: '大家不约而同鼓掌。',
    trap: '指一致行动。' },
  { id: 1246, word: '才华横溢', pinyin: 'cái huá héng yì', tier: '低频',
    meaning: '才华充分显露出来，形容很有才华。',
    distinguish: '褒义，指才华出众。',
    example: '他才华横溢。',
    trap: '指才华显露。' },
  { id: 1247, word: '沧海一粟', pinyin: 'cāng hǎi yī sù', tier: '低频',
    meaning: '大海里的一粒谷子，比喻非常渺小。',
    distinguish: '指极其渺小。',
    example: '个人如沧海一粟。',
    trap: '指渺小。' },
  { id: 1248, word: '草菅人命', pinyin: 'cǎo jiān rén mìng', tier: '低频',
    meaning: '把人命看作野草，指任意残杀人民。',
    distinguish: '贬义，指漠视人命。',
    example: '贪官草菅人命。',
    trap: '贬义，指轻视人命。' },
  { id: 1249, word: '侧目而视', pinyin: 'cè mù ér shì', tier: '低频',
    meaning: '斜着眼睛看人，形容畏惧、愤恨或鄙视。',
    distinguish: '含畏惧或鄙视。',
    example: '奸人令人侧目而视。',
    trap: '指畏惧/鄙视。' },
  { id: 1250, word: '参差不齐', pinyin: 'cēn cī bù qí', tier: '低频',
    meaning: '长短、高低不齐，形容不一致。',
    distinguish: '指不整齐。',
    example: '水平参差不齐。',
    trap: '指不一致。' },
  { id: 1251, word: '层出不穷', pinyin: 'céng chū bù qióng', tier: '低频',
    meaning: '接连不断地出现，没有穷尽。',
    distinguish: '指不断出现。',
    example: '新花样层出不穷。',
    trap: '指不断出现。' },
  { id: 1252, word: '畅所欲言', pinyin: 'chàng suǒ yù yán', tier: '低频',
    meaning: '尽情地说出想说的话。',
    distinguish: '指尽情发言。',
    example: '会上畅所欲言。',
    trap: '指尽情说。' },
  { id: 1253, word: '车水马龙', pinyin: 'chē shuǐ mǎ lóng', tier: '低频',
    meaning: '车如流水、马如游龙，形容车马往来不断、繁华热闹。',
    distinguish: '指繁华热闹。',
    example: '大街车水马龙。',
    trap: '指繁华热闹。' },
  { id: 1254, word: '称心如意', pinyin: 'chèn xīn rú yì', tier: '低频',
    meaning: '完全合乎心意。',
    distinguish: '指满意。',
    example: '生活称心如意。',
    trap: '指合乎心意。' },
  { id: 1255, word: '瞠目结舌', pinyin: 'chēng mù jié shé', tier: '低频',
    meaning: '瞪着眼睛说不出话，形容受窘或惊呆。',
    distinguish: '指惊呆。',
    example: '谎言令人瞠目结舌。',
    trap: '指惊讶说不出话。' },
  { id: 1256, word: '乘虚而入', pinyin: 'chéng xū ér rù', tier: '低频',
    meaning: '趁着空虚的地方进入，比喻趁弱点进攻。',
    distinguish: '指趁隙而入。',
    example: '敌军乘虚而入。',
    trap: '指趁弱进入。' },
  { id: 1257, word: '惩前毖后', pinyin: 'chéng qián bì hòu', tier: '低频',
    meaning: '吸取以前失败的教训，以后小心不重犯。',
    distinguish: '指吸取教训。',
    example: '总结教训，惩前毖后。',
    trap: '指以儆效尤。' },
  { id: 1258, word: '重整旗鼓', pinyin: 'chóng zhěng qí gǔ', tier: '低频',
    meaning: '失败后重新集合力量再干。',
    distinguish: '指东山再起、再干。',
    example: '他重整旗鼓，再战商场。',
    trap: '指重新振作。' },
  { id: 1259, word: '叱咤风云', pinyin: 'chì zhà fēng yún', tier: '低频',
    meaning: '一声呼喊、怒喝，就使风云变色，形容威力极大。',
    distinguish: '指威力浩大。',
    example: '英雄叱咤风云。',
    trap: '指气势威猛。' },
  { id: 1260, word: '宠辱不惊', pinyin: 'chǒng rǔ bù jīng', tier: '低频',
    meaning: '受宠或受辱都不动心，形容豁达。',
    distinguish: '褒义，指淡泊。',
    example: '他宠辱不惊。',
    trap: '指不计得失。' },
  { id: 1261, word: '踌躇满志', pinyin: 'chóu chú mǎn zhì', tier: '低频',
    meaning: '对自己取得的成就非常得意。',
    distinguish: '指得意满足。',
    example: '他踌躇满志。',
    trap: '指得意。' },
  { id: 1262, word: '出尔反尔', pinyin: 'chū ěr fǎn ěr', tier: '低频',
    meaning: '说了又翻悔，指说话不算数。',
    distinguish: '贬义，指反复无常、不守信用。',
    example: '承诺不可出尔反尔。',
    trap: '贬义，指失信。' },
  { id: 1263, word: '出神入化', pinyin: 'chū shén rù huà', tier: '低频',
    meaning: '技艺达到高超绝妙的境界。',
    distinguish: '褒义，指技艺极妙。',
    example: '琴艺出神入化。',
    trap: '指技艺高妙。' },
  { id: 1264, word: '触目惊心', pinyin: 'chù mù jīng xīn', tier: '低频',
    meaning: '看到某种严重情况引起内心震动。',
    distinguish: '指震惊。',
    example: '灾情触目惊心。',
    trap: '指震惊。' },
  { id: 1265, word: '垂涎欲滴', pinyin: 'chuí xián yù dī', tier: '低频',
    meaning: '馋得口水要滴下来，形容极其贪婪。',
    distinguish: '贬义，指贪婪。',
    example: '他对财富垂涎欲滴。',
    trap: '指贪馋。' },
  { id: 1266, word: '唇亡齿寒', pinyin: 'chún wáng chǐ hán', tier: '低频',
    meaning: '嘴唇没了，牙齿就会冷，比喻关系密切、利害相关。',
    distinguish: '指依存关系。',
    example: '邻国相依，唇亡齿寒。',
    trap: '指利害相关。' },
  { id: 1267, word: '从容不迫', pinyin: 'cóng róng bù pò', tier: '低频',
    meaning: '不慌不忙，沉着镇定。',
    distinguish: '褒义，指镇定。',
    example: '他从容不迫地应对。',
    trap: '指镇定。' },
  { id: 1268, word: '粗枝大叶', pinyin: 'cū zhī dà yè', tier: '低频',
    meaning: '比喻做事不细致、粗心大意。',
    distinguish: '贬义，指粗糙。',
    example: '工作粗枝大叶易出错。',
    trap: '指不细致。' },
  { id: 1269, word: '错落有致', pinyin: 'cuò luò yǒu zhì', tier: '低频',
    meaning: '交错纷杂而有情趣。',
    distinguish: '指布局巧妙。',
    example: '院落错落有致。',
    trap: '指交错有致。' },
  { id: 1270, word: '大公无私', pinyin: 'dà gōng wú sī', tier: '低频',
    meaning: '完全为人民利益着想，毫无私心。',
    distinguish: '褒义，指公正无私。',
    example: '他大公无私。',
    trap: '指公正无私。' },
  { id: 1271, word: '大相径庭', pinyin: 'dà xiāng jìng tíng', tier: '低频',
    meaning: '彼此相差很远或矛盾很大。',
    distinguish: '指差别很大。',
    example: '说法大相径庭。',
    trap: '指相差很大。' },
  { id: 1272, word: '淡泊明志', pinyin: 'dàn bó míng zhì', tier: '低频',
    meaning: '不追求名利，才能显示志向高远。',
    distinguish: '褒义，指清心寡欲。',
    example: '他淡泊明志，潜心学术。',
    trap: '指不慕名利。' },
  { id: 1273, word: '当局者迷', pinyin: 'dāng jú zhě mí', tier: '低频',
    meaning: '下棋的人反而糊涂，比喻当事人往往糊涂。',
    distinguish: '常与「旁观者清」连用。',
    example: '当局者迷，旁观者清。',
    trap: '指当事人糊涂。' },
  { id: 1274, word: '当机立断', pinyin: 'dāng jī lì duàn', tier: '低频',
    meaning: '抓住时机，立刻决断。',
    distinguish: '褒义，指果断。',
    example: '险情当前，当机立断。',
    trap: '指果断决策。' },
  { id: 1275, word: '道貌岸然', pinyin: 'dào mào àn rán', tier: '低频',
    meaning: '神态庄严，常含装作正经、实际虚伪。',
    distinguish: '贬义，指外表正经。',
    example: '他道貌岸然，内心龌龊。',
    trap: '贬义，指伪正经。' },
  { id: 1276, word: '得过且过', pinyin: 'dé guò qiě guò', tier: '低频',
    meaning: '只要勉强过得去就过下去，指敷衍度日。',
    distinguish: '贬义，指苟安。',
    example: '工作不可得过且过。',
    trap: '贬义，指敷衍。' },
  { id: 1277, word: '登峰造极', pinyin: 'dēng fēng zào jí', tier: '低频',
    meaning: '登上顶峰，比喻达到最高点（多指学问、技艺）。',
    distinguish: '可褒可贬，指达到极点。',
    example: '伪造之技登峰造极。',
    trap: '指达到极点。' },
  { id: 1278, word: '等量齐观', pinyin: 'děng liàng qí guān', tier: '低频',
    meaning: '对有差别的事物同等看待。',
    distinguish: '多用于否定，指一视同仁。',
    example: '二者不能等量齐观。',
    trap: '指同等看待。' },
  { id: 1279, word: '滴水穿石', pinyin: 'dī shuǐ chuān shí', tier: '低频',
    meaning: '水滴不断可穿透石头，比喻坚持不懈终能成功。',
    distinguish: '褒义，指持之以恒。',
    example: '滴水穿石，贵在坚持。',
    trap: '指坚持有成。' },
  { id: 1280, word: '颠沛流离', pinyin: 'diān pèi liú lí', tier: '低频',
    meaning: '生活艰难、四处流浪。',
    distinguish: '指困苦流浪。',
    example: '战乱中颠沛流离。',
    trap: '指流离失所。' },
  { id: 1281, word: '顶天立地', pinyin: 'dǐng tiān lì dì', tier: '低频',
    meaning: '形容形象高大、气概雄伟豪迈。',
    distinguish: '褒义，指堂堂正正。',
    example: '好男儿顶天立地。',
    trap: '指气概豪迈。' },
  { id: 1282, word: '独当一面', pinyin: 'dú dāng yī miàn', tier: '低频',
    meaning: '单独负责一个方面的工作。',
    distinguish: '指能独立负责。',
    example: '他已能独当一面。',
    trap: '指独力承担。' },
  { id: 1283, word: '断章取义', pinyin: 'duàn zhāng qǔ yì', tier: '低频',
    meaning: '不顾全篇，只取一段或一句曲解原意。',
    distinguish: '贬义，指曲解。',
    example: '引用不可断章取义。',
    trap: '贬义，指割裂曲解。' },
  { id: 1284, word: '对牛弹琴', pinyin: 'duì niú tán qín', tier: '低频',
    meaning: '对牛弹琴，比喻对不懂道理的人讲道理。',
    distinguish: '贬义，指说话不看对象。',
    example: '对他说教如对牛弹琴。',
    trap: '指说话无的放矢。' },
  { id: 1285, word: '咄咄怪事', pinyin: 'duō duō guài shì', tier: '低频',
    meaning: '令人惊讶的怪事。',
    distinguish: '指奇怪的事。',
    example: '竟有此等咄咄怪事。',
    trap: '指奇怪事。' },
  { id: 1286, word: '阿谀奉承', pinyin: 'ē yú fèng chéng', tier: '低频',
    meaning: '巴结讨好别人。',
    distinguish: '贬义，指谄媚。',
    example: '他惯会阿谀奉承。',
    trap: '贬义，指讨好。' },
  { id: 1287, word: '防患未然', pinyin: 'fáng huàn wèi rán', tier: '低频',
    meaning: '在祸患发生前就加以预防。',
    distinguish: '指事前预防。',
    example: '安全要防患未然。',
    trap: '指事前防范。' },
  { id: 1288, word: '防不胜防', pinyin: 'fáng bù shèng fáng', tier: '低频',
    meaning: '要防备的太多，防备不过来。',
    distinguish: '指难以尽防。',
    example: '骗局防不胜防。',
    trap: '指难防。' },
  { id: 1289, word: '飞黄腾达', pinyin: 'fēi huáng téng dá', tier: '低频',
    meaning: '比喻官职、地位上升很快。',
    distinguish: '多指仕途顺遂。',
    example: '他平步青云，飞黄腾达。',
    trap: '指迅速得势。' },
  { id: 1290, word: '废寝忘食', pinyin: 'fèi qǐn wàng shí', tier: '低频',
    meaning: '顾不得睡觉、忘记吃饭，形容专心努力。',
    distinguish: '褒义，指专心。',
    example: '他废寝忘食攻关。',
    trap: '指专注忘我。' },
  { id: 1291, word: '分崩离析', pinyin: 'fēn bēng lí xī', tier: '低频',
    meaning: '形容集团、国家分裂瓦解。',
    distinguish: '指瓦解崩溃。',
    example: '旧阵营分崩离析。',
    trap: '指分裂瓦解。' },
  { id: 1292, word: '风烛残年', pinyin: 'fēng zhú cán nián', tier: '低频',
    meaning: '风中的蜡烛、残余的岁月，比喻临近死亡的晚年。',
    distinguish: '指晚年将尽。',
    example: '他已风烛残年。',
    trap: '指晚年将逝。' },
  { id: 1293, word: '扶危济困', pinyin: 'fú wēi jì kùn', tier: '低频',
    meaning: '扶助处境危急、救济困难的人。',
    distinguish: '褒义，指行善。',
    example: '他扶危济困，乐善好施。',
    trap: '指救助困危。' },
  { id: 1294, word: '改头换面', pinyin: 'gǎi tóu huàn miàn', tier: '低频',
    meaning: '只改外表、内容不变，比喻只换形式不换实质。',
    distinguish: '贬义，指换汤不换药。',
    example: '宣传改头换面。',
    trap: '贬义，指形式改变。' },
  { id: 1295, word: '刚愎自用', pinyin: 'gāng bì zì yòng', tier: '低频',
    meaning: '十分固执自信，不听取别人意见。',
    distinguish: '贬义，指固执。',
    example: '他刚愎自用，终致失败。',
    trap: '贬义，指固执己见。' },
  { id: 1296, word: '高瞻远瞩', pinyin: 'gāo zhān yuǎn zhǔ', tier: '低频',
    meaning: '站得高、看得远，比喻眼光远大。',
    distinguish: '褒义，指眼光长远。',
    example: '领袖高瞻远瞩。',
    trap: '指眼光远大。' },
  { id: 1297, word: '隔靴搔痒', pinyin: 'gé xuē sāo yǎng', tier: '低频',
    meaning: '隔着靴子挠痒，比喻说话做事不切实际、不解决问题。',
    distinguish: '指不得要领。',
    example: '批评隔靴搔痒。',
    trap: '指不中要害。' },
  { id: 1298, word: '功成名就', pinyin: 'gōng chéng míng jiù', tier: '低频',
    meaning: '功业建立、名声成就。',
    distinguish: '褒义，指事业有成。',
    example: '他功成名就，告老还乡。',
    trap: '指功业成就。' },
  { id: 1299, word: '孤芳自赏', pinyin: 'gū fāng zì shǎng', tier: '低频',
    meaning: '自命清高、自我欣赏。',
    distinguish: '多含贬义，指自命不凡。',
    example: '他孤芳自赏，不合群。',
    trap: '指自命清高。' },
  { id: 1300, word: '孤陋寡闻', pinyin: 'gū lòu guǎ wén', tier: '低频',
    meaning: '学识浅陋、见闻不广。',
    distinguish: '贬义，指学识浅。',
    example: '不可孤陋寡闻。',
    trap: '指见闻少。' },
  { id: 1301, word: '固若金汤', pinyin: 'gù ruò jīn tāng', tier: '低频',
    meaning: '形容城池或阵地坚固，不易攻破。',
    distinguish: '指极其坚固。',
    example: '城防固若金汤。',
    trap: '指防御坚固。' },
  { id: 1302, word: '故弄玄虚', pinyin: 'gù nòng xuán xū', tier: '低频',
    meaning: '故意玩弄使人迷惑的欺骗手段。',
    distinguish: '贬义，指故作神秘。',
    example: '他故弄玄虚，吓唬人。',
    trap: '贬义，指故作神秘。' },
  { id: 1303, word: '顾全大局', pinyin: 'gù quán dà jú', tier: '低频',
    meaning: '照顾整个大局，使之不受损害。',
    distinguish: '褒义，指识大体。',
    example: '做事要顾全大局。',
    trap: '指从整体着眼。' },
  { id: 1304, word: '拐弯抹角', pinyin: 'guǎi wān mò jiǎo', tier: '低频',
    meaning: '沿着弯弯曲曲的路走，比喻说话绕弯、不直截了当。',
    distinguish: '指说话不直。',
    example: '有话直说，别拐弯抹角。',
    trap: '指曲折不直接。' },
  { id: 1305, word: '光明磊落', pinyin: 'guāng míng lěi luò', tier: '低频',
    meaning: '胸怀坦白，正大光明。',
    distinguish: '褒义，指心地坦白。',
    example: '他光明磊落，襟怀坦荡。',
    trap: '指正直坦白。' },
  { id: 1306, word: '广开言路', pinyin: 'guǎng kāi yán lù', tier: '低频',
    meaning: '尽量创造让人们发表意见的条件。',
    distinguish: '指鼓励进言。',
    example: '治国当广开言路。',
    trap: '指广纳意见。' },
  { id: 1307, word: '过眼云烟', pinyin: 'guò yǎn yún yān', tier: '低频',
    meaning: '从眼前飘过的云烟，比喻很快就消失的事物。',
    distinguish: '指转瞬即逝。',
    example: '名利如过眼云烟。',
    trap: '指很快消逝。' },
  { id: 1308, word: '骇人听闻', pinyin: 'hài rén tīng wén', tier: '低频',
    meaning: '使人听了非常吃惊（多指坏事）。',
    distinguish: '指事情可怕；与「耸人听闻」不同。',
    example: '惨案骇人听闻。',
    trap: '指可怕之事。' },
  { id: 1309, word: '含辛茹苦', pinyin: 'hán xīn rú kǔ', tier: '低频',
    meaning: '忍受辛苦，形容备受艰难。',
    distinguish: '褒义，指忍受劳苦。',
    example: '母亲含辛茹苦抚育儿女。',
    trap: '指受尽辛苦。' },
  { id: 1310, word: '汗流浃背', pinyin: 'hàn liú jiā bèi', tier: '低频',
    meaning: '汗流得满背都是，形容极度惶恐或劳累。',
    distinguish: '指大汗淋漓。',
    example: '他忙得汗流浃背。',
    trap: '指汗出很多。' },
  { id: 1311, word: '好逸恶劳', pinyin: 'hào yì wù láo', tier: '低频',
    meaning: '贪图安逸、厌恶劳动。',
    distinguish: '贬义，指懒惰。',
    example: '他好逸恶劳，难成大事。',
    trap: '贬义，指贪安逸。' },
  { id: 1312, word: '和盘托出', pinyin: 'hé pán tuō chū', tier: '低频',
    meaning: '比喻全部说出来，毫不保留。',
    distinguish: '指全盘说出。',
    example: '他把真相和盘托出。',
    trap: '指全部倒出。' },
  { id: 1313, word: '和衷共济', pinyin: 'hé zhōng gòng jì', tier: '低频',
    meaning: '大家一条心，共同渡过江河，比喻同心协力。',
    distinguish: '褒义，指同心协力。',
    example: '上下和衷共济。',
    trap: '指同心协力。' },
  { id: 1314, word: '鹤发童颜', pinyin: 'hè fà tóng yán', tier: '低频',
    meaning: '白白的头发、红润的面色，形容老人气色好。',
    distinguish: '指老当益壮之貌。',
    example: '老者鹤发童颜。',
    trap: '指老人健朗。' },
  { id: 1315, word: '横征暴敛', pinyin: 'héng zhēng bào liǎn', tier: '低频',
    meaning: '强征捐税，搜刮人民财富。',
    distinguish: '贬义，指残酷剥削。',
    example: '暴政横征暴敛。',
    trap: '贬义，指苛税。' },
  { id: 1316, word: '鸿篇巨制', pinyin: 'hóng piān jù zhì', tier: '低频',
    meaning: '篇幅宏大的著作。',
    distinguish: '指长篇巨著。',
    example: '他著成鸿篇巨制。',
    trap: '指大著作。' },
  { id: 1317, word: '厚此薄彼', pinyin: 'hòu cǐ bó bǐ', tier: '低频',
    meaning: '重视这个、轻视那个，指待遇不公平。',
    distinguish: '指偏袒不公。',
    example: '对待下属不可厚此薄彼。',
    trap: '指偏袒。' },
  { id: 1318, word: '虎头蛇尾', pinyin: 'hǔ tóu shé wěi', tier: '低频',
    meaning: '头大如虎、尾细如蛇，比喻开头大、结尾小，有始无终。',
    distinguish: '贬义，指有头无尾。',
    example: '计划虎头蛇尾。',
    trap: '指有始无终。' },
  { id: 1319, word: '怀才不遇', pinyin: 'huái cái bù yù', tier: '低频',
    meaning: '有才能却遇不到赏识重用的人。',
    distinguish: '指才高无门。',
    example: '他怀才不遇，郁郁寡欢。',
    trap: '指才不被用。' },
  { id: 1320, word: '涣然冰释', pinyin: 'huàn rán bīng shì', tier: '低频',
    meaning: '像冰遇热消融，形容疑虑、误会一下子消除。',
    distinguish: '指疑虑消散。',
    example: '误会涣然冰释。',
    trap: '指消散。' },
  { id: 1321, word: '恍然大悟', pinyin: 'huǎng rán dà wù', tier: '低频',
    meaning: '一下子明白过来。',
    distinguish: '指猛然醒悟。',
    example: '听此一言，恍然大悟。',
    trap: '指猛然明白。' },
  { id: 1322, word: '祸起萧墙', pinyin: 'huò qǐ xiāo qiáng', tier: '低频',
    meaning: '祸乱发生在家里，比喻内部发生祸乱。',
    distinguish: '指内乱；"萧墙"指内部。',
    example: '团队祸起萧墙。',
    trap: '指内部生乱。' },
  { id: 1323, word: '急中生智', pinyin: 'jí zhōng shēng zhì', tier: '低频',
    meaning: '在紧急中想出好办法。',
    distinguish: '褒义，指临危有智。',
    example: '他急中生智，脱困而出。',
    trap: '指急迫生智。' },
  { id: 1324, word: '集腋成裘', pinyin: 'jí yè chéng qiú', tier: '低频',
    meaning: '狐狸腋下的皮虽小，聚集起来能缝成皮袍，比喻积少成多。',
    distinguish: '褒义，指积少成多。',
    example: '捐款集腋成裘。',
    trap: '指积少成多。' },
  { id: 1325, word: '寄人篱下', pinyin: 'jì rén lí xià', tier: '低频',
    meaning: '依附别人生活，不能自立。',
    distinguish: '指依附他人。',
    example: '他不愿寄人篱下。',
    trap: '指依附生活。' },
  { id: 1326, word: '既往不咎', pinyin: 'jì wǎng bù jiù', tier: '低频',
    meaning: '对过去的错误不再追究。',
    distinguish: '指不究既往。',
    example: '此事既往不咎。',
    trap: '指不追旧过。' },
  { id: 1327, word: '坚韧不拔', pinyin: 'jiān rèn bù bá', tier: '低频',
    meaning: '形容意志坚定，不可动摇。',
    distinguish: '褒义，指意志坚强。',
    example: '他坚韧不拔地奋斗。',
    trap: '指意志坚定。' },
  { id: 1328, word: '艰苦卓绝', pinyin: 'jiān kǔ zhuó jué', tier: '低频',
    meaning: '形容斗争十分艰苦，超出寻常。',
    distinguish: '褒义，指极艰苦。',
    example: '长征艰苦卓绝。',
    trap: '指极艰苦。' },
  { id: 1329, word: '间不容发', pinyin: 'jiān bù róng fà', tier: '低频',
    meaning: '中间容不下一根头发，比喻与灾祸相距极近。',
    distinguish: '指极为危急。',
    example: '险情间不容发。',
    trap: '指极危急。' },
  { id: 1330, word: '见异思迁', pinyin: 'jiàn yì sī qiān', tier: '低频',
    meaning: '看见别的事物就改变主意，指意志不坚定。',
    distinguish: '贬义，指易变心。',
    example: '择业不可见异思迁。',
    trap: '贬义，指动摇。' },
  { id: 1331, word: '剑拔弩张', pinyin: 'jiàn bá nǔ zhāng', tier: '低频',
    meaning: '剑出鞘、弓拉满，形容形势紧张、一触即发。',
    distinguish: '指局势紧张。',
    example: '双方剑拔弩张。',
    trap: '指一触即发。' },
  { id: 1332, word: '箭在弦上', pinyin: 'jiàn zài xián shàng', tier: '低频',
    meaning: '箭已搭在弦上，比喻事情已经到了不得不发的地步。',
    distinguish: '指势在必行。',
    example: '改革箭在弦上。',
    trap: '指不得不发。' },
  { id: 1333, word: '娇生惯养', pinyin: 'jiāo shēng guàn yǎng', tier: '低频',
    meaning: '从小被宠爱纵容，形容娇弱任性。',
    distinguish: '贬义，指被溺爱。',
    example: '他娇生惯养，吃不得苦。',
    trap: '指被溺爱。' },
  { id: 1334, word: '脚踏实地', pinyin: 'jiǎo tà shí dì', tier: '低频',
    meaning: '脚踏在坚实的土地上，比喻做事踏实认真。',
    distinguish: '褒义，指踏实。',
    example: '做事要脚踏实地。',
    trap: '指踏实。' },
  { id: 1335, word: '解甲归田', pinyin: 'jiě jiǎ guī tián', tier: '低频',
    meaning: '脱下铠甲，回家种地，指军人退伍还乡。',
    distinguish: '指退役回乡。',
    example: '将军解甲归田。',
    trap: '指退伍回乡。' }
];
module.exports = { IDIOMS_FILLER };
